version: '3.3'
services:
  database:
    build: ./database/
    image: docker.pkg.github.com/cwxlab/osiaas/database:stein
    container_name: database
    hostname: database
    volumes:
      - type: bind
        source: /var/opt/hosting/cwxlab/osiaas/database/var/lib/mysql/
        target: /var/lib/mysql/
      - type: bind
        source: /opt/hosting/cwxlab/osiaas/database/etc/mysql/mariadb.cond.d/99-openstack.conf
        target: /etc/mysql/mariadb.conf.d/99-openstack.conf
        read_only: true
    ports:
      - "3306:3306"
  keystone:
    build: ./keystone/
    image: docker.pkg.github.com/cwxlab/osiaas/keystone:stein
    container_name: keystone
    hostname: keystone
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /opt/hosting/cwxlab/osiaas/keystone/etc/keystone/keystone.conf
        target: /etc/keystone/keystone.conf
        read_only: true
      - type: bind
        source: /opt/hosting/cwxlab/osiaas/keystone/etc/keystone/fernet-keys/
        target: /etc/keystone/fernet-keys/
      - type: bind
        source: /opt/hosting/cwxlab/osiaas/keystone/etc/keystone/credential-keys/
        target: /etc/keystone/credential-keys/
